version: 2
registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: "/.github"
    registries:
      - public-nuget
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    ignore:
       # See https://github.com/dotnet/aspire/issues/7123
      - dependency-name: "OpenTelemetry.*"
    groups:
      Aspire:
        patterns:
          - "Aspire.*"
          - "Microsoft.Extensions.ServiceDiscovery.*"
      AspNetCore:
        patterns:
          - "Microsoft.AspNetCore.*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions.*"
          - "Microsoft.Bcl.*"
      Grpc:
        patterns:
          - "Grpc.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      MicrosoftTest:
        patterns:
          - "Microsoft.NET.Test.*"
      xunit:
        patterns:
          - "xunit*"
      Orleans:
        patterns:
          - "Microsoft.Orleans*"
    labels:
      - area-engineering-systems

  - package-ecosystem: npm
    directory: "samples/AspireWithJavaScript/AspireJavaScript.Angular"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      angular-core:
        patterns:
          - "@angular/*"
          - "@angular/cli"
          - "zone.js"
          - "rxjs"
      angular-tooling:
        patterns:
          - "@angular-devkit/*"
          - "typescript"
          - "@types/*"
          - "eslint*"
          - "karma*"
          - "webpack*"
      misc-deps:
        patterns:
          - "*"
    labels:
      - area-engineering-systems

  - package-ecosystem: npm
    directory: "samples/AspireWithJavaScript/AspireJavaScript.React"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      react-core:
        patterns:
          - "react"
          - "react-dom"
      react-tooling:
        patterns:
          - "typescript"
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "vite*"
          - "webpack*"
      misc-deps:
        patterns:
          - "*"
    labels:
      - area-engineering-systems

  - package-ecosystem: npm
    directory: "samples/AspireWithJavaScript/AspireJavaScript.Vue"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      vue-core:
        patterns:
          - "vue"
          - "@vue/*"
          - "vue-router"
          - "pinia"
      vue-tooling:
        patterns:
          - "vite*"
          - "typescript"
          - "@types/*"
          - "eslint*"
      misc-deps:
        patterns:
          - "*"
    labels:
      - area-engineering-systems

  - package-ecosystem: npm
    directory: "samples/AspireWithNode/NodeFrontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - area-engineering-systems

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - area-engineering-systems
